### ISSUE TITLE
Support record type 17

### ISSUE THREAD

**Issue by 3r1co** [ivosh/node-nist#20]
Hello,
could you please add record type 17 to your library?
I could also create a pull request if this is more suitable for you.
Thanks a lot and kind regards
Eric

**Comment by ivosh** [comment]
Hi Eric, certainly a PR for Type-17 (iris image record) is preferred.
Please could you share how do you consume this library (from a Node project, from a .NET project...)?

**Comment by 3r1co** [comment]
Hi Ivo,
I created the pull request (https://github.com/ivosh/node-nist/pull/21). 
I'm using this library as part of a node project as it integrats well with the test framwork I'm using (https://github.com/mock-server/mockserver)
Thanks for being so reactive!
Eric

**Comment by ivosh** [comment]
Almost two years have passed since the PR submission. Still no test cases provided.
