### ISSUE TITLE
Decode from string does not seem to work. Encoding problem?

### ISSUE THREAD

**Issue by Edza** [ivosh/node-nist#4]
I generated a nist file using nistEncode from the default example. I then tried to decode it.

```
let input = "1.001:1131.002:05021.003:112001.004:CRM1.005:201907171.007:DAI0354541.008:ORI385743541.009:TCN2487S0542.001:562.002:002.004:John2.005:Doe2.007:1978-05-12";


result = nistLib.nistDecode(
```

Got error:

```
{ error:
   { category: 'NIST',
     code: 'NIST_DECODE_ERROR',
     detail: 'Cannot find NIST file separator between offsets [0, 168].',
     endOffset: 168,
     nistSource: undefined,
     source: undefined,
     startOffset: 0 },
  tag: 'failure' }
```

What worked was directly passing the value:
nistDecode(nistEncode(...)) - works

However when I copy the output from nistEncode into a .txt file, then into a string, the nistDecode returns the given error. Some encoding problem?

**Comment by ivosh** [comment]
NIST traditional encoding is a binary format. 
When you copied it via clipboard, some binary data got garbled.
Be very careful **not** to process NIST files as text.

**Comment by Edza** [comment]
What I am doing is calling your library from ASP.NET core. It serializes and deserializes all data. Looks like some .NET automatic encoding serialization is causing me some problems.

 Isn't ANSI/NIST encoded in 7 bit ascii? That is a text encdoing.

**Comment by ivosh** [comment]
ANSI/NIST-ITL 1-2011 specifies two encodings - traditional (binary) one and XML one.
This library deals with the binary one which is widely spread in the industry.
Therefore you need to treat your input and output as a pure binary.

You cannot simply declare:
``
let input = "1.001:113�1.002:0502�1.003:1�1�2�00�1.004:CRM�1.005:20190717�1.007:DAI035454�1.008:ORI38574354�1.009:TCN2487S054�2.001:56�2.002:00�2.004:John�2.005:Doe�2.007:1978-05-12�";
``

You already have a problem in your input string. Instead, you need to encode the input string in a binary format, such as found in https://github.com/ivosh/node-nist/blob/master/src/nistDecode.test.ts (look for `Buffer.from`).

**Comment by Edza** [comment]
Thanks for the help.

I managed to get a call from .NET working! :D

https://github.com/JeringTech/Javascript.NodeJS/issues/72

**Comment by ivosh** [comment]
Congratulations!
