### ISSUE TITLE
Support record Type 7, Image Data (User-defined)

### ISSUE THREAD

**Issue by MaxAlex666** [ivosh/node-nist#6]
Hi, great project, could you extend it with support for records type 7, Image Data (User-defined)?

**Comment by ivosh** [comment]
Hei Maxim,
Are you using binary (traditional) encoding? For Type-7 to be useful, you would need to supply your own decoding/encoding schema. Otherwise you get just 7.001, 7.002 and the rest of data as one big binary blob.
Do you have an example of a NIST file with a decoding schema?

**Comment by MaxAlex666** [comment]
Hi Ivosh, yes you're right, a custom set of fields is used when filling out this entry (standard only the first two fields LEN and IDC).
Is it possible to encode a custom field structure using your library? (Uses traditional binary encoding)
And a similar question: how can I create composite fields? (for example, fields 1.013 / 1.015)

**Comment by ivosh** [comment]
Hi Maxim,
For composite fields, please refer to https://github.com/ivosh/node-nist/blob/master/src/index.ts#L29

For the custom Type-7 encoding, I assume it can be done similarly to the following examples:
https://github.com/ivosh/node-nist/blob/master/src/testNistEncoding.ts#L82
https://github.com/ivosh/node-nist/blob/master/src/testNistDecoding.ts

However the problem with Type-7 is that it uses completely custom (binary) encoding, unlike the "text" encoding used for example for Type-2 or Type-10 (which also allow custom fields).

Do you have an example of a NIST file with an encoding/decoding schema?

**Comment by MaxAlex666** [comment]
Hi Ivo, sent the file by mail.
